In [2]:
import pandas as pd

student_data = {
    "temp" : [24, 21, 23],
    "is_raining" : [False, True, False],
    "is_holiday" : [True, False, False],
    "student_count" : [231, 120, 150]
}

df = pd.DataFrame(student_data)

   temp  is_raining  is_holiday  student_count
0    24       False        True            231
1    21        True       False            120
2    23       False       False            150

In [4]:
df.tail(2)

   temp  is_raining  is_holiday  student_count
1    21        True       False            120
2    23       False       False            150

In [ ]:
path = "../datasets/titanic/titanic_full.csv"
df = pd.read_csv(path)

In [13]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,WikiId,Age_wiki,Class
count,1309.000000,891.000000,1309.000000,1046.000000,1309.000000,1309.000000,1308.000000,1304.000000,1302.000000,1304.000000
mean,655.000000,0.383838,2.294882,29.881138,0.498854,0.385027,33.295479,658.534509,29.415829,2.291411
std,378.020061,0.486592,0.837836,14.413493,1.041658,0.865560,51.758668,380.377373,13.758954,0.840852
min,1.000000,0.000000,1.000000,0.170000,0.000000,0.000000,0.000000,1.000000,0.170000,1.000000
25%,328.000000,0.000000,2.000000,21.000000,0.000000,0.000000,7.895800,326.750000,21.000000,1.750000
50%,655.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200,661.500000,28.000000,3.000000
75%,982.000000,1.000000,3.000000,39.000000,1.000000,0.000000,31.275000,987.250000,37.750000,3.000000
max,1309.000000,1.000000,3.000000,80.000000,8.000000,9.000000,512.329200,1314.000000,74.000000,3.000000

In [23]:
df[['Name', 'Age', 'Sex']].head(1400)

                                                   Name   Age     Sex
0                               Braund, Mr. Owen Harris  22.0    male
1     Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  female
2                                Heikkinen, Miss. Laina  26.0  female
3          Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  female
4                              Allen, Mr. William Henry  35.0    male
...                                                 ...   ...     ...
1304                                 Spector, Mr. Woolf   NaN    male
1305                       Oliva y Ocana, Dona. Fermina  39.0  female
1306                       Saether, Mr. Simon Sivertsen  38.5    male
1307                                Ware, Mr. Frederick   NaN    male
1308                           Peter, Master. Michael J   NaN    male

[1309 rows x 3 columns]

In [33]:
survived_females = df[(df['Sex'] == 'female') & (df['Survived'] == 1)]
survived_males = df[(df['Sex'] == 'male') & (df['Survived'] == 1)]

In [37]:
survived_males.to_csv("survived males data.csv", index=False)