In [6]:
import pandas as pd

df = pd.read_csv('../datasets/titanic/titanic_full.csv')

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 21 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  1309 non-null   int64
 1   Survived     891 non-null    float64
 2   Pclass       1309 non-null   int64
 3   Name         1309 non-null   str
 4   Sex          1309 non-null   str
 5   Age          1046 non-null   float64
 6   SibSp        1309 non-null   int64
 7   Parch        1309 non-null   int64
 8   Ticket       1309 non-null   str
 9   Fare         1308 non-null   float64
 10  Cabin        295 non-null    str
 11  Embarked     1307 non-null   str
 12  WikiId       1304 non-null   float64
 13  Name_wiki    1304 non-null   str
 14  Age_wiki     1302 non-null   float64
 15  Hometown     1304 non-null   str
 16  Boarded      1304 non-null   str
 17  Destination  1304 non-null   str
 18  Lifeboat     502 non-null    str
 19  Body         130 non-null    str
 20  Class        1304 non-null   float64
dtypes: float64(6), int64(4), str(11)
memory usage: 214.9 KB

In [7]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,WikiId,Age_wiki,Class
count,1309.000000,891.000000,1309.000000,1046.000000,1309.000000,1309.000000,1308.000000,1304.000000,1302.000000,1304.000000
mean,655.000000,0.383838,2.294882,29.881138,0.498854,0.385027,33.295479,658.534509,29.415829,2.291411
std,378.020061,0.486592,0.837836,14.413493,1.041658,0.865560,51.758668,380.377373,13.758954,0.840852
min,1.000000,0.000000,1.000000,0.170000,0.000000,0.000000,0.000000,1.000000,0.170000,1.000000
25%,328.000000,0.000000,2.000000,21.000000,0.000000,0.000000,7.895800,326.750000,21.000000,1.750000
50%,655.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200,661.500000,28.000000,3.000000
75%,982.000000,1.000000,3.000000,39.000000,1.000000,0.000000,31.275000,987.250000,37.750000,3.000000
max,1309.000000,1.000000,3.000000,80.000000,8.000000,9.000000,512.329200,1314.000000,74.000000,3.000000

In [18]:
df[['Name','Age']].tail().describe()

             Age
count   2.000000
mean   38.750000
std     0.353553
min    38.500000
25%    38.625000
50%    38.750000
75%    38.875000
max    39.000000

In [ ]:
survived_females = df[(df['Sex'] == 'female') & (df['Survived'] == 1)][['Name','Age', 'Fare']]

survived_females.to_csv('Survived Females List.html')