In [3]:
import pandas as pd

In [12]:
strudent_count_data = {
    "day_count": [1, 2, 3, 4, 5, 6],
    "is_raining": [True, False, True, False, True, False],
    "is_weekend": [False, False, True, True, False, False],
    "temperature": [30, 25, 28, 22, 27, 24],
    "students_count": [20, 30, 15, 25, 18, 22]
}

df = pd.DataFrame(strudent_count_data)

df.head(6)

   day_count  is_raining  is_weekend  temperature  students_count
0          1        True       False           30              20
1          2       False       False           25              30
2          3        True        True           28              15
3          4       False        True           22              25
4          5        True       False           27              18
5          6       False       False           24              22

In [8]:
df.tail(3)

   day_count  is_raining  is_weekend  temperature  students_count
3          4       False        True           22              25
4          5        True       False           27              18
5          6       False       False           24              22

In [14]:
# Reading data from a CSV file
path = "../datasets/titanic/titanic_full.csv"
df = pd.read_csv(path)

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 21 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  1309 non-null   int64
 1   Survived     891 non-null    float64
 2   Pclass       1309 non-null   int64
 3   Name         1309 non-null   str
 4   Sex          1309 non-null   str
 5   Age          1046 non-null   float64
 6   SibSp        1309 non-null   int64
 7   Parch        1309 non-null   int64
 8   Ticket       1309 non-null   str
 9   Fare         1308 non-null   float64
 10  Cabin        295 non-null    str
 11  Embarked     1307 non-null   str
 12  WikiId       1304 non-null   float64
 13  Name_wiki    1304 non-null   str
 14  Age_wiki     1302 non-null   float64
 15  Hometown     1304 non-null   str
 16  Boarded      1304 non-null   str
 17  Destination  1304 non-null   str
 18  Lifeboat     502 non-null    str
 19  Body         130 non-null    str
 20  Class        1304 non-null   float64
dtypes: float64(6), int64(4), str(11)
memory usage: 214.9 KB

In [34]:
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,...,Embarked,WikiId,Name_wiki,Age_wiki,Hometown,Boarded,Destination,Lifeboat,Body,Class
0,1,0.0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,...,S,691.0,"Braund, Mr. Owen Harris",22.0,"Bridgerule, Devon, England",Southampton,"Qu'Appelle Valley, Saskatchewan, Canada",NaN,NaN,3.0
1,2,1.0,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,...,C,90.0,"Cumings, Mrs. Florence Briggs (née Thayer)",35.0,"New York, New York, US",Cherbourg,"New York, New York, US",4,NaN,1.0
2,3,1.0,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,...,S,865.0,"Heikkinen, Miss Laina",26.0,"Jyväskylä, Finland",Southampton,New York City,14?,NaN,3.0
3,4,1.0,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,...,S,127.0,"Futrelle, Mrs. Lily May (née Peel)",35.0,"Scituate, Massachusetts, US",Southampton,"Scituate, Massachusetts, US",D,NaN,1.0
4,5,0.0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,...,S,627.0,"Allen, Mr. William Henry",35.0,"Birmingham, West Midlands, England",Southampton,New York City,NaN,NaN,3.0

In [29]:
df[['Name', 'Age', 'Sex', 'Fare']].head(7)

                                                Name   Age     Sex     Fare
0                            Braund, Mr. Owen Harris  22.0    male   7.2500
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  female  71.2833
2                             Heikkinen, Miss. Laina  26.0  female   7.9250
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  female  53.1000
4                           Allen, Mr. William Henry  35.0    male   8.0500
5                                   Moran, Mr. James   NaN    male   8.4583
6                            McCarthy, Mr. Timothy J  54.0    male  51.8625

In [33]:
df[df['Sex'] == 'female'][['Name', 'Age']].describe()

              Age
count  388.000000
mean    28.687088
std     14.576962
min      0.170000
25%     19.000000
50%     27.000000
75%     38.000000
max     76.000000

In [43]:
female_survived = df[(df['Sex'] ==  'female') & (df['Survived'] == 1)][['Age', 'Name']]
male_survived = df[(df['Sex'] ==  'male') & (df['Survived'] == 1)][['Age', 'Name']]

In [45]:
female_survived.to_csv('Survived Females List.csv')

In [42]:
print(f"Female survived: {female_survived[0]}")
print(f"Male survived: {male_survived[0]}")

Female survived: 233
Male survived: 109