In [1]:
import pandas as pd

In [5]:
student_count_data = {
    "day_count": [1, 2, 3, 4, 5, 6],
    "is_raining": [True, False, True, False, True, False],
    "is_weekend": [False, False, True, True, False, False],
    "temperature": [30, 25, 28, 22, 27, 24],
    "students_count": [20, 30, 15, 25, 18, 22]
}

df = pd.DataFrame(student_count_data)
df

   day_count  is_raining  is_weekend  temperature  students_count
0          1        True       False           30              20
1          2       False       False           25              30
2          3        True        True           28              15
3          4       False        True           22              25
4          5        True       False           27              18
5          6       False       False           24              22

In [15]:
df = pd.read_csv('../datasets/titanic/titanic_full.csv')

df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,WikiId,Age_wiki,Class
count,1309.000000,891.000000,1309.000000,1046.000000,1309.000000,1309.000000,1308.000000,1304.000000,1302.000000,1304.000000
mean,655.000000,0.383838,2.294882,29.881138,0.498854,0.385027,33.295479,658.534509,29.415829,2.291411
std,378.020061,0.486592,0.837836,14.413493,1.041658,0.865560,51.758668,380.377373,13.758954,0.840852
min,1.000000,0.000000,1.000000,0.170000,0.000000,0.000000,0.000000,1.000000,0.170000,1.000000
25%,328.000000,0.000000,2.000000,21.000000,0.000000,0.000000,7.895800,326.750000,21.000000,1.750000
50%,655.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200,661.500000,28.000000,3.000000
75%,982.000000,1.000000,3.000000,39.000000,1.000000,0.000000,31.275000,987.250000,37.750000,3.000000
max,1309.000000,1.000000,3.000000,80.000000,8.000000,9.000000,512.329200,1314.000000,74.000000,3.000000

In [24]:
df[["Name", "Age", "Sex"]].describe()

               Age
count  1046.000000
mean     29.881138
std      14.413493
min       0.170000
25%      21.000000
50%      28.000000
75%      39.000000
max      80.000000

In [30]:
# Data Filtering
df[(df["Age"] >= 30) &  (df["Age"] <= 50)].tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,...,Embarked,WikiId,Name_wiki,Age_wiki,Hometown,Boarded,Destination,Lifeboat,Body,Class
1295,1296,NaN,1,"Frauenthal, Mr. Isaac Gerald",male,43.0,1,0,17765,27.7208,...,C,122.0,"Frauenthal, Mr. Isaac Gerald",43.0,"London, England, UK",Southampton,"New York, New York, US",5,NaN,1.0
1298,1299,NaN,1,"Widener, Mr. George Dunton",male,50.0,1,1,113503,211.5000,...,C,316.0,"Widener, Mr. George Dunton",50.0,"Philadelphia, Pennsylvania, US",Southampton,"Philadelphia, Pennsylvania, US",NaN,NaN,1.0
1302,1303,NaN,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,...,Q,206.0,"Minahan, Mrs. Lillian E. (née Thorpe)",37.0,"Fond du Lac, Wisconsin, US",Southampton,"Fond du Lac, Wisconsin, US",14,NaN,1.0
1305,1306,NaN,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,...,C,229.0,"and maid, Doña Fermina Oliva y Ocana",39.0,"Madrid, Spain",Cherbourg,"New York, New York, US",8,NaN,1.0
1306,1307,NaN,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,...,S,1169.0,"Sæther, Mr. Simon Sivertsen",43.0,"Skaun, Sør-Trøndelag, Norway",Southampton,US,NaN,32MB,3.0

In [39]:
female_survived = df[(df['Sex'] == 'female') & (df['Survived'] == 1)]
male_survived = df[(df['Sex'] == 'male') & (df['Survived'] == 1)]

female_survived.to_html('female Survived.html')