In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv('titanic_cleaned.csv')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,WikiId,Name_wiki,Hometown,Boarded,Destination,Class
0,1,0.0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,691.0,"Braund, Mr. Owen Harris","Bridgerule, Devon, England",Southampton,"Qu'Appelle Valley, Saskatchewan, Canada",3.0
1,2,1.0,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,90.0,"Cumings, Mrs. Florence Briggs (née Thayer)","New York, New York, US",Cherbourg,"New York, New York, US",1.0
2,3,1.0,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,865.0,"Heikkinen, Miss Laina","Jyväskylä, Finland",Southampton,New York City,3.0
3,4,1.0,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,127.0,"Futrelle, Mrs. Lily May (née Peel)","Scituate, Massachusetts, US",Southampton,"Scituate, Massachusetts, US",1.0
4,5,0.0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,627.0,"Allen, Mr. William Henry","Birmingham, West Midlands, England",Southampton,New York City,3.0

In [ ]:
df = df[['Survived', 'Age', 'Fare', 'Pclass', 'SibSp', 'Parch']]
df.describe()

# 50, 100, 150, 200
# .25, .5, .75, 1

,Survived,Age,Fare,Pclass,SibSp,Parch
count,1302.000000,1302.000000,1302.000000,1302.000000,1302.000000,1302.000000
mean,0.260369,29.476705,33.074558,2.297235,0.500768,0.384793
std,0.439004,12.900992,51.536689,0.836325,1.043813,0.866233
min,0.000000,0.170000,0.000000,1.000000,0.000000,0.000000
25%,0.000000,22.000000,7.895800,2.000000,0.000000,0.000000
50%,0.000000,28.000000,14.454200,3.000000,0.000000,0.000000
75%,1.000000,35.000000,31.206250,3.000000,1.000000,0.000000
max,1.000000,80.000000,512.329200,3.000000,8.000000,9.000000

In [7]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [11]:
scaler = StandardScaler()
df[['Age', 'Fare']] = scaler.fit_transform(df[['Age', 'Fare']])

In [14]:
df.to_csv('titanic_scaled.csv')